version: '3'

services:
  roomsservice:
  
    build: .
   
    container_name: roomsservice

    command: "python manage.py runserver 0.0.0.0:8000" 
  
    
    volumes:
      - .:/usr/src/app
    
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
   
    image: postgres
 
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
   
    container_name: pgsqldb
     
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
