# Generated by Django 4.2.7 on 2023-11-20 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms_app", "0002_bookng_end_booking_bookng_start_booking_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_booking", models.DateField(null=True)),
                ("end_booking", models.DateField(null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name="room",
            managers=[
                ("free_rooms", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(name="Bookng", ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="rooms_app.room",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
